spring:
  datasource:
    url: 'jdbc:h2:file:./database;CASE_INSENSITIVE_IDENTIFIERS=true'
    username: 'sa'
    password: ''
  data:
    jdbc:
      repositories:
        enabled: false

springtricks.module-number: 6
